#!/bin/bash
# ~/.bash_stuff/bash_exports
# ENV
BASH_ENV=~/.bashrc
#USER
USERNAME=$(whoami)
#PATH
#export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/android-sdk/tools/:/opt/android-sdk/platform-tools/:/opt/kde/bin:/usr/bin/perlbin/site:/usr/bin/perlbin/vendor:/usr/bin/perlbin/core:/opt/qt/bin:$(ruby -rubygems -e "puts Gem.user_dir")/bin:/usr/local/bin:$HOME/bin

#export LANG="en_US.UTF-8"
LANG=en_US.UTF-8
#export LC_ALL=
LC_ALL=
#export LC_COLLATE="C"
LC_COLLATE="C"
#export TMPDIR="$HOME/tmp"
TMPDIR=~/tmp
#export EDITOR="vim"
EDITOR=vim
#export PAGER="vimpager"
PAGER=vimpager
HISTCONTROL=ignoreboth
#export HISTCONTROL="ignoreboth"
HISTCONTROL=ignoreboth
#export HISTIGNORE='history*'
HISTIGNORE=history*
#export PROMPT_COMMAND='history -a;echo -en "\e]2;";history 1|sed "s/^[ \t]*[0-9]\{1,\}  //g";echo -en "\e\\";'
PROMPT_COMMAND='history -a;echo -en "\e]2;";history 1|sed "s/^[ \t]*[0-9]\{1,\}  //g";echo -en "\e\\";'
#export SDL_AUDIODRIVER="alsa"
SDL_AUDIODRIVER=alsa
#export SDL_VIDEO_FULLSCREEN_HEAD=1
SDL_VIDEO_FULLSCREEN_HEAD=1
#export DISPLAY=:0.0
#DISPLAY=:0.0
#if [ -n "$DISPLAY" ]; then
#    #    export BROWSER="dwb"
#        BROWSER="dwb"
#    else
#    #    export BROWSER="elinks"
#        BROWSER="elinks"
#    fi
#export GTK_IM_MODULE=xims
GTK_IM_MODULE=xims

# CCACHE
#USE_CCACHE=1
#CCACHE_DIR=~/android/.ccache

export PATH=${PATH}:$HOME/bin
export USERNAME BASH_ENV TMPDIR PATH EDITOR LANG LC_ALL LC_COLLATE EDITOR PAGER HISTCONTROL HISTCONTROL HISTIGNORE PROMPT_COMMAND SDL_AUDIODRIVER SDL_VIDEO_FULLSCREEN_HEAD BROWSER GTK_IM_MODULE

