#!/usr/bin/env bash
#--------------------------------------------
# file:     ~/.bash_stuff/bash_prompt
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#--------------------------------------------
source ~/.git-prompt.sh
# PS Lines
export PS2='continue> '
export PS3='choose: '
export PS4='|${BASH_SOURCE} ${LINENO}${FUNCNAME[0]:+ ${FUNCNAME[0]}()}|  '
if [ -n "$SSH_CLIENT" ]; then
    PS1="\[\033[0;31m\]┌─\[\033[0;37m\][\[\e[0;96m\]\h \[\e[0;91m\]\W\[\e[0;37m\]$(__git_ps1 " (%s)") \[\033[0;37m\][\[\033[0;31m\]SSH\[\033[0;37m\]]\n\[\033[0;31m\]└─╼\[\033[0m\] "
else
   PS1='\[\e[0;91m\]┌─\[\033[0;37m\][\[\e[0;96m\]\h \[\e[0;91m\]\W\[\e[0;37m\]$(__git_ps1 " (%s)") \[\033[0;37m\]]\n\[\e[0;91m\]└─╼\[\033[0m\] '
fi

# vim: set filetype=bash:
