#!/bin/bash
# Bash Colors
# ~/.bash_stuff/bash_colors
#

    # regular colors
    local K="\[\033[0;30m\]"    # black
    local R="\[\033[0;31m\]"    # red
    local G="\[\033[0;32m\]"    # green
    local Y="\[\033[0;33m\]"    # yellow
    local B="\[\033[0;34m\]"    # blue
    local M="\[\033[0;35m\]"    # magenta
    local C="\[\033[0;36m\]"    # cyan
    local W="\[\033[0;37m\]"    # white
    local O="\[\e[0;33m\]"    # orange
    local P="\[\e[0;35m\]"    # purple
    local LG="\[\e[0;37m\]"   # lightgray
    local DG="\[\e[0;90m\]"   # darkgray
    local GL="\[\e[0;92m\]"   # lightgreen
    local LR="\[\e[0;91m\]"   # lightred
    local LP="\[\e[0;95m\]"   # lightpurple
    local TQ="\[\e[0;96m\]"   # tourquoise

    # emphasized (bolded) colors
    local EMK="\[\033[1;30m\]"
    local EMR="\[\033[1;31m\]"
    local EMG="\[\033[1;32m\]"
    local EMY="\[\033[1;33m\]"
    local EMB="\[\033[1;34m\]"
    local EMM="\[\033[1;35m\]"
    local EMC="\[\033[1;36m\]"
    local EMW="\[\033[1;37m\]"
    local EMO="\[\e[1;43m\]"  # orange
    local EMP="\[\e[1;105m\]"  # purple

    # background colors
    local BGK="\[\033[40m\]"
    local BGR="\[\033[41m\]"
    local BGG="\[\033[42m\]"
    local BGY="\[\033[43m\]"
    local BGB="\[\033[44m\]"
    local BGM="\[\033[45m\]"
    local BGC="\[\033[46m\]"
    local BGW="\[\033[47m\]"
    local BGO="\[\e[1;43m\]"  # Orange
    local BGP="\[\e[1;45m\]"  # Purple
