#!/bin/bash
# ~/.bash_stuff/bash_exports

#!/bin/bash
# ~/.bash_stuff/bash_exports

# BASH_ENV
BASH_ENV=~/.bashrc
# USER
USERNAME=$(whoami)

# LANG
LANG=en_US.UTF-8

# LC_ALL
LC_ALL=

# LC_COLLATE
LC_COLLATE="C"

# TMPDIR
TMPDIR=~/tmp

# EDITOR
EDITOR=vim

# PAGER
PAGER=vimpager

# HISTCONTROL
HISTCONTROL=ignoreboth

# HISTIGNORE
HISTIGNORE=history*

# PROMPT_COMMAND
PROMPT_COMMAND='history -a;echo -en "\e]2;";history 1|sed "s/^[ \t]*[0-9]\{1,\}  //g";echo -en "\e\\";'

# SDL_AUDIODRIVER
SDL_AUDIODRIVER=alsa

# SDL_VIDEO_FULLSCREEN_HEAD
SDL_VIDEO_FULLSCREEN_HEAD=1

# DISPLAY
#DISPLAY=:0.0
#if [ -n "$DISPLAY" ]; then
#    #    export BROWSER="dwb"
#        BROWSER="dwb"
#    else
#    #    export BROWSER="elinks"
#        BROWSER="elinks"
#    fi

# GTK_IM_MODULE
GTK_IM_MODULE=xims

#### START ANDROID NEEDS ####

# JAVA_JDK
#export J2SDKDIR=/opt/java6
#export PATH=$PATH:/opt/java6/bin:/opt/java6/db/bin
#export JAVA_HOME=/opt/java6
#export DERBY_HOME=/opt/java6/db

# JAVA_JRE
#export PATH=$PATH:/opt/java6/jre/bin
#export JAVA_HOME=${JAVA_HOME:-/opt/java6/jre}

# ANDROID_JAVA_HOME
ANDROID_JAVA_HOME=$JAVA_HOME

# ANDROID_SDK
#export ANDROID_HOME=/opt/android-sdk
#export ANDROID_SWT=/opt/android-sdk/tools/lib/x86/swt.jar
#export ANDROID_SWT=$ANDROID_HOME/tools/lib/x86_64
#export PATH=$PATH:$ANDROID_HOME/tools
#export PATH=$PATH:/opt/android-sdk/platform-tools

# ANDROID_SDK
#export PATH=$PATH:/opt/android-ndk
#export ANDROID_NDK=/opt/android-ndk

# CCACHE
export USE_CCACHE=1
export CCACHE_DIR=~/android/.ccache

#### END ANDROID NEEDS ####

# EXPORT PATH
export PATH=${PATH}:$HOME/bin

# EXPORT ALL
export USERNAME BASH_ENV TMPDIR PATH EDITOR LANG LC_ALL LC_COLLATE EDITOR PAGER HISTCONTROL HISTCONTROL HISTIGNORE PROMPT_COMMAND SDL_AUDIODRIVER SDL_VIDEO_FULLSCREEN_HEAD BROWSER GTK_IM_MODULE ANDROID_JAVA_HOME CCACHE

