#!/bin/bash
# ~/.bash_stuff/bash_exports

#PATH
export PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/java/jre/bin:/opt/android-sdk/platform-tools/:/opt/kde/bin:/usr/bin/perlbin/site:/usr/bin/perlbin/vendor:/usr/bin/perlbin/core:/opt/qt/bin:$(ruby -rubygems -e "puts Gem.user_dir")/bin:/usr/local/bin:$HOME/.bin

if [ -n "$DISPLAY" ]; then
    export BROWSER="chromium"
else
    export BROWSER="elinks"
fi

export LANG="en_US.UTF-8"
export LC_ALL=
export LC_COLLATE="C"
export TMPDIR="$HOME/tmp"
export EDITOR="vim"
export PAGER="vimpager"
export HISTCONTROL="ignoreboth"
export HISTIGNORE='history*'
export PROMPT_COMMAND='history -a;echo -en "\e]2;";history 1|sed "s/^[ \t]*[0-9]\{1,\}  //g";echo -en "\e\\";'
export SDL_AUDIODRIVER="alsa"
export DISPLAY=:0.0
export SDL_VIDEO_FULLSCREEN_HEAD=1
export JAVA_HOME="/usr/bin/java"
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
export PATH
export USERNAME BASH_ENV PATH
export GTK_IM_MODULE=xims

