#!/usr/bin/env bash
#--------------------------------------------
# file:     ~/.bash_stuff/bash_binds
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#--------------------------------------------

