#!/usr/bin/env bash
#--------------------------------------------
# file:     ~/.bash_stuff/bash_prompt
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#--------------------------------------------
source ~/.git-completion.bash
#source ~/.git-prompt.sh
# PS Lines
#export PS2='continue> '
#export PS3='choose: '
#export PS4='|${BASH_SOURCE} ${LINENO}${FUNCNAME[0]:+ ${FUNCNAME[0]}()}|  '
if [ -n "$SSH_CLIENT" ]; then
#    PS1='[\u@\h \W$(__git_ps1 " (%s\[\033[0;37m\])")]\$ '
    PS1='\[\033[0;31m\]┌─\[\e[0;96m\]<\[\e[0;28m\]SSH\[\e[0;96m\]>\[\033[0;37m\][\[\e[0;96m\]\h \[\e[0;91m\]\W\[\e[0;37m\]$(__git_ps1 " \[\e[0;96m\](\[\e[0;96m\]%s\[\e[0;96m\])")\[\033[0;37m\]]\n\[\033[0;31m\]└─╼\[\033[0m\] '
else
   PS1='\[\e[0;96m\]┌─\[\e[0;92m\][\[\e[0;91m\]\h \[\e[0;37m\]\W\[\033[0;37m\]$(__git_ps1 " \[\033[0;37m\](\[\e[0;96m\]%s\[\033[0;37m\])") \[\e[0;92m\]]\n\[\e[0;96m\]└─╼\[\033[0m\] '
fi

# if .git-prompt.sh exists, set options and execute it
if [ -f ~/.git-prompt.sh ]; then
  GIT_PS1_SHOWDIRTYSTATE=true
  GIT_PS1_SHOWSTASHSTATE=true
  GIT_PS1_SHOWUNTRACKEDFILES=true
  GIT_PS1_SHOWUPSTREAM="auto"
  GIT_PS1_HIDE_IF_PWD_IGNORED=true
  GIT_PS1_SHOWCOLORHINTS=true
  . ~/.git-prompt.sh
fi

# vim: set filetype=bash:
