#!/usr/bin/env bash
#----------------------------------------------
# file:     ~/.bash_stuff/files/android
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#----------------------------------------------

alias adb="/opt/android-sdk/platform-tools/adb"
alias fastboot="/opt/android-sdk/platform-tools/fastboot"
alias reposyncf="time repo sync -j$( nproc --all ) --force-sync -c --no-clone-bundle --no-tags --optimized-fetch --prune"

# exports
# JAVA_JDK
#J2SDKDIR=/opt/java6
#PATH=$PATH:/opt/java6/bin:/opt/java6/db/bin
#JAVA_HOME=/opt/java6
#DERBY_HOME=/opt/java6/db

# JAVA_JRE
#export PATH=$PATH:/opt/java6/jre/bin
#export JAVA_HOME=${JAVA_HOME:-/opt/java6/jre}

# ANDROID_SDK
#ANDROID_HOME=/opt/android-sdk
#ANDROID_SWT=/opt/android-sdk/tools/lib/x86/swt.jar
#ANDROID_SWT=$ANDROID_HOME/tools/lib/x86_64
#PATH=$PATH:$ANDROID_HOME/tools
#PATH=$PATH:/opt/android-sdk/platform-tools
#PATH=$PATH:$ANDROID_HOME/build-tools/26.0.2

# ANDROID_NDK
#PATH=$PATH:/opt/android-ndk
#ANDROID_NDK="/opt/android-ndk"

# ARM
#ARM_ROOT=/opt/android-ndk
#ARM_INC=$ARM_ROOT/platforms/android-9/arch-arm/usr/include/
#ARM_LIB=$ARM_ROOT/platforms/android-9/arch-arm/usr/lib/
#ARM_TOOL=$ARM_ROOT/toolchains/arm-linux-androideabi-4.7/prebuilt/linux-x86
#ARM_LIBO=$ARM_TOOL/lib/gcc/arm-linux-androideabi/4.7/
#ARM_PRE=arm-eabi

# UPDATE ANDROID-SDK
alias android-sdk-update="/opt/android-sdk/tools/android update sdk --no-ui"

# make commands

# tcp/ip
alias modtcp="sudo sysctl -w net.ipv4.tcp_window_scaling=0"

# repo commands
alias reposj1="repo sync -j1"
alias reposfj1="repo sync -f -j1"

# export
#export USE_CCACHE CCACHE_DIR 

# build ready source
alias source4build="source ~/android/.aliases/android_aliases"
# official build aquarios
alias aquaofficial="source ~/android/.aliases/aquarios-aliases"
# AQUA OFFICAL BUILD SETUP
alias aquabuildprep="source ~/anddoid/.aliases/android_aliases;source ~/android/.aliases/aquarios_aliases"

# virtualenv2
alias virtenv="virtualenv2 venv;source venv/bin/activate"

# vim: set filetype=bash:
