#!/usr/bin/env bash
#----------------------------------------------
# file:     ~/.bash_stuff/files/android
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#----------------------------------------------

alias adb="/opt/android-sdk/platform-tools/adb"
alias fastboot="/opt/android-sdk/platform-tools/fastboot"
alias reposyncf="time repo sync -j$( nproc --all ) --force-sync -c --no-clone-bundle --no-tags --optimized-fetch --prune"

# exports
# JAVA_JDK
#J2SDKDIR=/opt/java6
#PATH=$PATH:/opt/java6/bin:/opt/java6/db/bin
#JAVA_HOME=/opt/java6
#DERBY_HOME=/opt/java6/db

# JAVA_JRE
#export PATH=$PATH:/opt/java6/jre/bin
#export JAVA_HOME=${JAVA_HOME:-/opt/java6/jre}

# ANDROID_JAVA_HOME
#ANDROID_JAVA_HOME="/usr/lib/jvm/java-8-openjdk"

# ANDROID_SDK
#ANDROID_HOME=/opt/android-sdk
#ANDROID_SWT=/opt/android-sdk/tools/lib/x86/swt.jar
#ANDROID_SWT=$ANDROID_HOME/tools/lib/x86_64
#PATH=$PATH:$ANDROID_HOME/tools
#PATH=$PATH:/opt/android-sdk/platform-tools
#PATH=$PATH:$ANDROID_HOME/build-tools/26.0.2

# ANDROID_NDK
#PATH=$PATH:/opt/android-ndk
ANDROID_NDK=/opt/android-ndk

# ARM
#ARM_ROOT=/opt/android-ndk
#ARM_INC=$ARM_ROOT/platforms/android-9/arch-arm/usr/include/
#ARM_LIB=$ARM_ROOT/platforms/android-9/arch-arm/usr/lib/
#ARM_TOOL=$ARM_ROOT/toolchains/arm-linux-androideabi-4.7/prebuilt/linux-x86
#ARM_LIBO=$ARM_TOOL/lib/gcc/arm-linux-androideabi/4.7/
#ARM_PRE=arm-eabi

# CCACHE
USE_CCACHE="1"
CCACHE_DIR="$HOME/android/.ccache"

# android sdk
alias android-sdk-update="/opt/android-sdk/tools/android update sdk --no-ui"
alias android-buildenv="source ~/android/.extra/android_aliases"

# build scripts
#alias buildashamu="sh ~/android/scripts/build/build_raum.sh"
#alias buildaokpjb="sh ~/android/scripts/build/build_rom-aokp_jb.sh"
#alias buildparadigm="sh ~/android/scripts/build/build_rom-bamf_paradigm.sh"

# make commands
alias aquashamu=". build/envsetup.sh;make clobber;brunch shamu-userdebug"
alias aquaberkeley=". build/envsetup.sh;lunch berkeley-userdebug;make clobber;mka systemimage -j8"

# tcp/ip
alias modtcp="sudo sysctl -w net.ipv4.tcp_window_scaling=0"

# repo commands
alias reposj1="repo sync -j1"
alias reposfj1="repo sync -f -j1"

alias fetchlmanifest="curl -L -o .repo/local_manifest.xml -O -L https://raw.github.com/pax10/local_manifest/rb/local_manifest.xml"

# export
export ANDROID_NDK USE_CCACHE CCACHE_DIR

# vim: set filetype=bash:
