#!/usr/bin/env bash
#--------------------------------------------
# file:     ~/.bash_stuff/bash_colors
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#--------------------------------------------

    TR='\[\033[0m\]'      # Text Reset
    # regular colors
    K='\[\033[0;30m\]'    # black
    R='\[\033[0;31m\]'    # red
    G='\[\033[0;32m\]'    # green
    Y='\[\033[0;33m\]'    # yellow
    B='\[\033[0;34m\]'    # blue
    M='\[\033[0;35m\]'    # magenta
    C='\[\033[0;36m\]'    # cyan
    W='\[\033[0;37m\]'    # white
    O='\[\e[0;33m\]'    # orange
    P='\[\e[0;35m\]'    # purple
    LG='\[\e[0;37m\]'   # lightgray
    DG='\[\e[0;90m\]'   # darkgray
    GL='\[\e[0;92m\]'   # lightgreen
    LR='\[\e[0;91m\]'   # lightred
    LP='\[\e[0;95m\]'   # lightpurple
    TQ='\[\e[0;96m\]'   # tourquoise

    # emphasized (bolded) colors
    EMK='\[\033[1;30m\]'
    EMR='\[\033[1;31m\]'
    EMG='\[\033[1;32m\]'
    EMY='\[\033[1;33m\]'
    EMB='\[\033[1;34m\]'
    EMM='\[\033[1;35m\]'
    EMC='\[\033[1;36m\]'
    EMW='\[\033[1;37m\]'
    EMO='\[\e[1;43m\]'  # orange
    EMP='\[\e[1;105m\]'  # purple

    # background colors
    BGK='\[\033[4]0m\]'
    BGR='\[\033[41m\]'
    BGG='\[\033[42m\]'
    BGY='\[\033[43m\]'
    BGB='\[\033[44m\]'
    BGM='\[\033[45m\]'
    BGC='\[\033[46m\]'
    BGW='\[\033[47m\]'
    BGO='\[\e[1;43m\]'  # Orange
    BGP='\[\e[1;45m\]'  # Purple

    UC=$W                 # user's color
    [ $UID -eq '0' ] && UC=$R   # root's color

# vim: set filetype=bash:
