#!/usr/bin/env bash
#----------------------------------------------
# file:     ~/.bash_stuff/files/irc
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#----------------------------------------------

# Fifo Nicklist Irssi
##################
#alias irsii="aterm -name aterm -title irssi -g 112x65+215+32 &"
#alias userlist="aterm -name aterm -title Ulist -g 17x30+1255+255 &"
#alias nicklist="cat $HOME/.irssi/nicklistfifo"


# vim: set filetype=bash:
