#!/usr/bin/env bash
#--------------------------------------------
# file:     ~/.bash_stuff/files/myaliases 
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#--------------------------------------------

# reset & source bash_profile
alias resetbash="reset;source $HOME/.bash_profile"
alias resetX="xrdb -merge $HOME/.Xresources"

# ls commands
alias lr='ls -R'                    # recursive ls
alias ll='ls -l'
alias la='ll -A'
alias lx='ll -BX'                   # sort by extension
alias lz='ll -rS'                   # sort by size
alias lt='ll -rt'                   # sort by date
alias lm='la | more'
#alias ls="ls --color=always"
alias lsl="ls -l --color=always"
alias lsal="ls -al --color=always"
alias lsA="ls -A --color=always"
alias lsAl="ls -Al --color=always"
alias lsg="ls --color=always | grep $@"
alias llee='tree --dirsfirst -ChFupDaLg 1'
alias listdira="ls -la | grep "^d" && ls -la | grep "^-" && ls -la | grep "^l""
alias listdirb="ls -la | grep "^d" && ls -la | grep -v "^d""

# cd commands
alias ~='cd ~'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
# cd and ls in one
cl() {
if [ -d "$1" ]; then
        cd "$1"
        ls
        else
        echo "bash: cl: '$1': Directory not found"
fi
}


## modified commands
alias a="ack -ia"
alias b="bundle exec"
alias diff='colordiff'              # requires colordiff package
alias grep='grep --color=auto'
alias more='less'
alias mkdir='mkdir -p -v'
alias ping='ping -c 5'
alias grep='GREP_COLOR="1;37;45" LANG=C grep --color=auto'
alias h="history"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
alias ip="curl -s http://checkip.dyndns.com/ | sed 's/[^0-9\.]//g'"
alias localip="ipconfig getifaddr en1"
alias mp="mvim -p"
alias rkt="racket -il xrepl"
alias da='date "+%A, %B %d, %Y [%T]"'
alias dat='date "+%Y-%m-%d %A    %T %Z"'
alias c="cal"
alias thismonth="cal -m $(date +"%m %Y" -d "this month")"
alias upT="uptime"
alias exi="clear;exit"
alias x="xinit"
alias reboot="reboot"
alias shutdown="shutdown -h now"
alias :q="exit"

## du, df
alias d="du -h -d=1"
alias df='df -h'
alias du='du -c -h'
alias mountedinfo="df -hT"

## safety features
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i' # 'rm -i' prompts for every file
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# clear commands
alias clr="clear"
alias clrls="clear; ls --color=auto"

# join multiple lines with space inbetween
alias joinmultilines='tr "\\n" " "'

# ps commands
alias hist='history | grep $1'      # requires an argument
alias openports='netstat --all --numeric --programs --inet --inet6'
alias pg='ps -Af | grep $1'
alias psax="ps ax --forest"
alias psuax="ps aux --forest"
alias psauf="ps -auxf"
alias pseo="ps -eo pcpu,pid,user,args | sort -k 1 -r"
alias pseo2txt="ps -eo pid,pcpu,comm | awk '{if ($2 > 4) print }' >> ~/.ps_eo_test.txt"
# iostat, mpstat commands
alias cpuusage="iostat -c"
alias cpuusagedelay="iostat -tc 2"
alias cpuALL="mpstat -P ALL"

## editor('s)
# nano
# vi(m)
alias view="vim -p -R"
alias vp="vim -p"
alias ebrc="vim $HOME/.bashrc && source $HOME/.bashrc"
alias ebrca="vim $HOME/.bash_aliases && source $HOME/.bashrc_aliases"
alias ebrcas="vim $HOME/.bash_aliases_ssh-ftp && source $HOME/.bashrc_aliases_ssh-ftp"
alias vim2html="$HOME/scripts/office/vim2html.sh "

#chmod
#############
alias 755="find . -type d -exec chmod 755 {} \;"
alias 644="find . -type f -exec chmod 644 {} \;"
alias 664="find . -type f -exec chmod 664 {} \;"
alias 775="find . -type f -exec chmod 775 {} \;"
alias chmoddir="find . -type d -exec chmod $@ {} \;"
alias chmodfile="find . -type d -exec chmod $@ {} \;"
alias grpdirrw="find . -type d -exec chmod ugo+rwx {} \;"
alias grpfilerw="find . -type f -exec chmod ugo+rw {} \;"

# calculator
calc() { echo "scale=3;$@" | bc -l ; }

# SSH Gen Keys
# ECDSA
alias genecdsa="ssh-keygen -t ecdsa -b 521 -C "$(whoami)@$(hostname)-$(date -I)""
# DSA
alias gendsa="ssh-keygen -t dsa -b 1024 -C "$(whoami)@$(hostname)-$(date -I)""
# RSA
alias genrsa="ssh-keygen -t rsa -b 4096 -C "$(whoami)@$(hostname)-$(date -I)""
#PAIMON
alias genrsapaimon="ssh-keygen -t rsa -b 4096 -C "typezero@paimon.64-b.it-$(date -I)""

# gotop statusbar
alias gotops="gotop -c mydark -s"
# gotop average cpu and statusbar
alias gotopas="gotop -c mydark -a -s"
# gotop minimal and statusbar
alias gotopms="gotop -c mydark -m -s"

# lynx
alias lynx="lynx -cfg=~/.lynxrc"

# vim: set filetype=bash:
