#!/usr/bin/env bash
#----------------------------------------------
# file:     ~/.bash_stuff/files/office
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#----------------------------------------------

# Office
##################
alias openpdf="apvlv "
alias massotf2ttf="$HOME/scripts/mass-otf2ttf.sh"
#alias oowriter="/usr/bin/soffice -writer"
#alias oocalc="/usr/bin/soffice -calc"
#alias ooimpress="/usr/bin/soffice -impress"
#alias oodraw="/usr/bin/soffice -draw"
#alias oomath="/usr/bin/soffice -math"
#alias oobase="/usr/bin/soffice -base"
#alias ooprintadmin="sudo /usr/bin/spadmin"


# vim: set filetype=bash:
