#!/usr/bin/env bash
#----------------------------------------------
# file:     ~/.bash_stuff/files/pcloud
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#----------------------------------------------

# pcloud with config
alias pclcmd="pclcmd --config=/home/typezero/.pclcmd.cfg"
