#!/bin/dash -f
# Configure wmii
wmiiscript=wmiirc # For wmii.sh
. wmii.sh

# Configuration Variables
MODKEY=Mod4
UP=k
DOWN=j
LEFT=h
RIGHT=l

# Bars
noticetimeout=5
noticebar=/rbar/!notice

# Colors tuples: "<text> <background> <border>"
#WMII_NORMCOLORS='#d7d1d1 #454a57 #909090'
#WMII_FOCUSCOLORS='#000000 #d7d1d1 #0a0a0a'
WMII_NORMCOLORS='#000000 #454a57 #0a0a0a'
WMII_FOCUSCOLORS='#d7d1d1 #454a57 #909090'

WMII_BACKGROUND='feh --bg-center /home/mredd/images/wallpapers/3120x1050-maggotworms-arch.png'
#WMII_BACKGROUND='feh --bg-center /home/mredd/images/wallpapers/Shapes.png'
WMII_FONT='-*-clean-*-*-*-*-12-*-*-*-*-*-*-*'

set -- $(echo $WMII_NORMCOLORS $WMII_FOCUSCOLORS)
WMII_TERM="urxvt -title 'shell'"
WMII_SOCIAL="urxvt -title Social -fn 'xft:Liberation Mono:pixelsize=13:antialias=true:hinting=true'"
WMII_WEBEDIT="urxvt -title WebEdit -fn 'xft:Liberation Mono:pixelsize=13:antialias=true:hinting=true'"
WMII_RSS="urxvt -title RSSFeeds -fn 'xft:Liberation Mono:pixelsize=13:antialias=true:hinting=true' -e canto --update"
WMII_FBROWSER="thunderbird"
#WMII_WBROWSER="sh ~/scripts/net/strttabbedvimprobable2.sh"
#WMII_WBROWSER="uzbl-tabbed"
WMII_WBROWSER="chromeplus"
WMII_MPLAYER="mplayer -ao alsa -vf pp=lb /dev/video0"
#WMII_MUSICPLAYER="urxvt -pixmap "$HOME/images/wallpapers/no_comment_hd_widescreen_wallpaper_880.jpeg" -title MOC -fn 'xft:Liberation Mono:pixelsize=12:antialias=true:hinting=true' -e mocp"
#WMII_MUSICPLAYER="urxvt -pixmap "$HOME/images/wallpapers/DoubleBot.jpg" -title MOC -fn 'xft:Liberation Mono:pixelsize=12:antialias=true:hinting=true' -e mocp"
#WMII_MUSICPLAYER="urxvt -title 'MOC' -e mocp"
WMII_MUSICPLAYER="sh $HOME/.wmii-hg/scripts/random-bg-rxvt.sh"
WMII_KDX="~/apps/kdx/KDXClient.lexe"
WMII_VIRTUALBOX="VirtualBox"

# Menu history
hist="$(wmiir namespace)/history"
histnum=5000

# Column Rules
wmiir write /colrules <<!
/gimp/ -> 15+68+31
/.*/ -> 62+38 # Golden Ratio
!

# Tagging Rules
wmiir write /tagrules <<!
#/VLC|MPlayer/ -> ~+art+haon
/VLC|MPlayer/ -> ~
/KDX.*/ -> ~
/screen|conkeror|uzbl-*|tabbed|vimprobable2|chromeplus/ -> +haon
#/gedit|leafpad/ -> +edit
#/ssh|web/ -> +web
/Gimp/ -> ~+art
/Boxee|boxee/ -> ~
!

# Status Bar Info
#WMII_STATUSCOLORS='#0a0a0a #72886d #2a2929i'
WMII_STATUSCOLORS='#d7d1d1 #454a57 #909090'
#WMII_STATUSCOLORS='#b7bec4 #03111b #44494d'
#WMII_STATUSCOLORS='#80724e #1e1512 #dbd5ba'
status() {
    echo -n $(date +'%R:%S %m/%d/%Y') 
}
#Uptime - Update
#WMII_UPTIMECOLORS='#0a0a0a #72886d #2a2929'
WMII_UPTIMECOLORS='#d7d1d1 #454a57 #909090'
#WMII_UPTIMECOLORS='#b7bec4 #03111b #44494d'
#WMII_UPTIMECOLORS='#80724e #1e1512 #dbc585'
uptimebar() {
        echo -n $($HOME/.wmii-hg/scripts/uptime.sh) "-" Updates: $(perl $HOME/scripts/conky-scripts/updates/arch-updates/conky-updates.pl)
}
#TEMPBar
#WMII_TEMPCOLORS='#0a0a0a #72886d #2a2929'
WMII_TEMPCOLORS='#d7d1d1 #454a57 #909090'
#WMII_TEMPCOLORS='#b7bec4 #03111b #44494d'
#WMII_TEMPCOLORS='#80724e #1e1512 #dbd5ba'
tempbar() {
        echo -n $($HOME/.wmii-hg/scripts/checktemp.sh)
}
#NETCOREBar
#WMII_NETCORECOLORS='#0a0a0a #72886d #2a2929'
WMII_NETCORECOLORS='#d7d1d1 #454a57 #909090'
#WMII_NETCORECOLORS='#b7bec4 #03111b #44494d'
#WMII_NETCORECOLORS='#80724e #1e1512 #dbc585'
netcorebar() {
        echo -n $($HOME/.wmii-hg/scripts/mcorebar.sh)
}
#WeatherBar
#WMII_WEATHERCOLORS='#0a0a0a #72886d #2a2929'
WMII_WEATHERCOLORS='#d7d1d1 #454a57 #909090'
#WMII_WEATHERCOLORS='#b7bec4 #03111b #44494d'
#WMII_WEATHERCOLORS='#80724e #1e1512 #dbd5ba'
weatherbar() {
        echo -n $($HOME/.wmii-hg/scripts/check_weather.sh)
}
#MOCBar
#WMII_MOCCOLORS='#0a0a0a #72886d #2a2929'
WMII_MOCCOLORS='#d7d1d1 #454a57 #909090'
#WMII_MOCCOLORS='#b7bec4 #03111b #44494d'
#WMII_MOCCOLORS='#80724e #1e1512 #dbc585'
mocbar() {
        echo -n $($HOME/.wmii-hg/scripts/mocplay.sh)
}

#VOLBar
#WMII_VOLCOLORS='#0a0a0a #72886d #2a2929'
WMII_VOLCOLORS='#d7d1d1 #454a57 #909090'
#WMII_VOLCOLORS='#b7bec4 #03111b #44494d'
#WMII_VOLCOLORS='#80724e #1e1512 #dbc585'
volbar() {
        echo -n $($HOME/.wmii-hg/scripts/vol-bar.sh)
}

local_events() { true;}
wi_runconf -s wmiirc_local

echo $WMII_NORMCOLORS | wmiir create $noticebar

# Event processing
events() {
	cat <<'!'
	# Events
	Event CreateTag
		echo "$WMII_NORMCOLORS" "$@" | wmiir create "/lbar/$@"
	Event DestroyTag
		wmiir remove "/lbar/$@"
	Event FocusTag
		wmiir xwrite "/lbar/$@" "$WMII_FOCUSCOLORS" "$@"
	Event UnfocusTag
		wmiir xwrite "/lbar/$@" "$WMII_NORMCOLORS" "$@"
	Event UrgentTag
		shift
		wmiir xwrite "/lbar/$@" "*$@"
	Event NotUrgentTag
		shift
		wmiir xwrite "/lbar/$@" "$@"
	Event LeftBarClick LeftBarDND
		shift
		wmiir xwrite /ctl view "$@"
	Event Unresponsive
		{
			client=$1; shift
			msg="The following client is not responding. What would you like to do?$wi_nl"
			resp=$(wihack -transient $client \
				      xmessage -nearmouse -buttons Kill,Wait -print \
				               "$msg $(wmiir read /client/sel/label)")
			if [ "$resp" = Kill ]; then
				wmiir xwrite /client/$client/ctl slay &
			fi
		}&
	Event Notice
		wmiir xwrite $noticebar $wi_arg

		kill $xpid 2>/dev/null # Let's hope this isn't reused...
		{ sleep $noticetimeout; wmiir xwrite $noticebar ' '; }&
		xpid = $!
	Menu Client-3-Delete
		wmiir xwrite /client/$1/ctl kill
	Menu Client-3-Kill
		wmiir xwrite /client/$1/ctl slay
	Menu Client-3-Fullscreen
		wmiir xwrite /client/$1/ctl Fullscreen on
	Event ClientMouseDown
		wi_fnmenu Client $2 $1 &
	Menu LBar-3-Delete
		tag=$1; clients=$(wmiir read "/tag/$tag/index" | awk '/[^#]/{print $2}')
		for c in $clients; do
			if [ "$tag" = "$(wmiir read /client/$c/tags)" ]; then
				wmiir xwrite /client/$c/ctl kill
			else
				wmiir xwrite /client/$c/tags -$tag
			fi
			if [ "$tag" = "$(wi_seltag)" ]; then
				newtag=$(wi_tags | awk -v't='$tag '
					$1 == t { if(!l) getline l
						  print l
						  exit }
					{ l = $0 }')
				wmiir xwrite /ctl view $newtag
			fi
		done
	Event LeftBarMouseDown
		wi_fnmenu LBar "$@" &
	# Actions
	Action quit
		wmiir xwrite /ctl quit
	Action exec
		wmiir xwrite /ctl exec "$@"
	Action rehash
		proglist $PATH >$progsfile
	Action status
		set +xv
		if wmiir remove /rbar/z_status 2>/dev/null; then
			sleep 2
		fi
		echo $WMII_STATUSCOLORS | wmiir create /rbar/z_status
		while status | wmiir write /rbar/z_status; do
			sleep 1
		done
	Action uptime
		set +xv
		if wmiir remove /rbar/y_uptime 2>/dev/null; then
			sleep 3
		fi
		echo $WMII_UPTIMECOLORS | wmiir create /rbar/y_uptime
		while uptimebar | wmiir write /rbar/y_uptime; do
			sleep 2
		done
	Action temp
		set +xv
		if wmiir remove /rbar/x_temp 2>/dev/null; then
			sleep 2
		fi
		echo $WMII_TEMPCOLORS | wmiir create /rbar/x_temp
		while tempbar | wmiir write /rbar/x_temp; do
			sleep 60
		done
	Action netcore
		set +xv
		if wmiir remove /rbar/w_netcore 2>/dev/null; then
			sleep 2
		fi
		echo $WMII_NETCORECOLORS | wmiir create /rbar/w_netcore
		while netcorebar | wmiir write /rbar/w_netcore; do
			sleep 60
		done
	Action weather
		set +xv
		if wmiir remove /rbar/v_weather 2>/dev/null; then
			sleep 2
		fi
		echo $WMII_WEATHERCOLORS | wmiir create /rbar/v_weather
		while weatherbar | wmiir write /rbar/v_weather; do
			sleep 60
		done
	Action vol
		set +xv
		if wmiir remove /rbar/u_vol 2>/dev/null; then
			sleep 2
		fi
		echo $WMII_VOLCOLORS | wmiir create /rbar/u_vol
		while volbar | wmiir write /rbar/u_vol; do
			sleep 1
		done
	Action moc
		set +xv
		if wmiir remove /rbar/u_moc 2>/dev/null; then
			sleep 2
		fi
		echo $WMII_MOCCOLORS | wmiir create /rbar/u_moc
		while mocbar | wmiir write /rbar/u_moc; do
			sleep 1
		done

	# Key Bindings
	Key $MODKEY-Control-t
		case $(wmiir read /keys | wc -l | tr -d ' \t\n') in
		0|1)
			echo -n "$Keys" | wmiir write /keys
			wmiir xwrite /ctl grabmod $MODKEY;;
		*)
			wmiir xwrite /keys $MODKEY-Control-t
			wmiir xwrite /ctl grabmod Mod3;;
		esac
	Key $MODKEY-space
		wmiir xwrite /tag/sel/ctl select toggle
	Key $MODKEY-d
		wmiir xwrite /tag/sel/ctl colmode sel default-max
	Key $MODKEY-Shift-s
		wmiir xwrite /tag/sel/ctl colmode sel +max
	Key $MODKEY-s
		wmiir xwrite /tag/sel/ctl colmode sel stack-max
	Key $MODKEY-m
		wmiir xwrite /tag/sel/ctl colmode sel stack+max
	Key $MODKEY-a
		action $(wi_actions | wimenu -h "${hist}.actions" -n $histnum) &
	Key $MODKEY-p
		eval wmiir setsid "$(wimenu -h "${hist}.progs" -n $histnum <$progsfile)" &
	Key $MODKEY-t
		wmiir xwrite /ctl view $(wi_tags | wimenu -h "${hist}.tags" -n 50) &
	Key $MODKEY-Return
		eval wmiir setsid $WMII_TERM &
        Key $MODKEY-Mod1-m
                eval wmiir setsid $WMII_MUSICPLAYER & 
        Key $MODKEY-n
		eval wmiir setsid $WMII_WBROWSER &
        Key $MODKEY-Shift-n
		eval wmiir setsid $WMII_FBROWSER &
        Key $MODKEY-b
		eval wmiir setsid $WMII_SOCIAL &
        Key $MODKEY-Shift-b
		eval wmiir setsid $WMII_WEBEDIT &
        Key $MODKEY-Mod1-n
                eval wmiir setsid $WMII_RSS &
        Key $MODKEY-Mod1-k
                eval wmiir setsid $WMII_KDX &
        Key $MODKEY-Mod1-v
                eval wmiir setsid $WMII_VIRTUALBOX & 
	Key $MODKEY-Shift-space
		wmiir xwrite /tag/sel/ctl send sel toggle
	Key $MODKEY-f
		wmiir xwrite /client/sel/ctl Fullscreen toggle
	Key $MODKEY-Shift-c
		wmiir xwrite /client/sel/ctl kill
	Key $MODKEY-Shift-t
		wmiir xwrite "/client/$(wmiir read /client/sel/ctl)/tags" $(wi_tags | wimenu -h "${hist}.tags" -n 50) &
	Key $MODKEY-$LEFT
		wmiir xwrite /tag/sel/ctl select left
	Key $MODKEY-$RIGHT
		wmiir xwrite /tag/sel/ctl select right
	Key $MODKEY-$DOWN
		wmiir xwrite /tag/sel/ctl select down
	Key $MODKEY-$UP
		wmiir xwrite /tag/sel/ctl select up
	Key $MODKEY-Control-$DOWN
		wmiir xwrite /tag/sel/ctl select down stack
	Key $MODKEY-Control-$UP
		wmiir xwrite /tag/sel/ctl select up stack
	Key $MODKEY-Shift-$LEFT
		wmiir xwrite /tag/sel/ctl send sel left
	Key $MODKEY-Shift-$RIGHT
		wmiir xwrite /tag/sel/ctl send sel right
	Key $MODKEY-Shift-$DOWN
		wmiir xwrite /tag/sel/ctl send sel down
	Key $MODKEY-Shift-$UP
		wmiir xwrite /tag/sel/ctl send sel up
!
	for i in 0 1 2 3 4 5 6 7 8 9; do
		cat <<'!'
	Key $MODKEY-$i
		wmiir xwrite /ctl view "$i"
	Key $MODKEY-Shift-$i
		wmiir xwrite /client/sel/tags "$i"
!
	done
}
wi_events <<!
$(events | sed 's/^	\|^        //')
$(local_events)
!
unset events local_events

# WM Configuration
wmiir write /ctl <<!
	font $WMII_FONT
	focuscolors $WMII_FOCUSCOLORS
	normcolors $WMII_NORMCOLORS
	grabmod $MODKEY
	border 0
        bar on top
!
# set wallpaper
$WMII_BACKGROUND

export WMII_FONT WMII_TERM
export WMII_FOCUSCOLORS WMII_SELCOLORS WMII_NORMCOLORS

# Misc
#scripts
progsfile="$(wmiir namespace)/.proglist"
action status &
action uptime &
action temp &
action netcore &
action weather &
action vol &
action moc &

wi_proglist $PATH >$progsfile &

# Setup Tag Bar
IFS="$wi_nl"
wmiir rm $(wmiir ls /lbar | sed 's,^,/lbar/,') >/dev/null
seltag=$(wmiir read /tag/sel/ctl | sed 1q)
unset IFS
wi_tags | while read tag
do
	if [ "$tag" = "$seltag" ]; then
		echo "$WMII_FOCUSCOLORS" "$tag"
	else
		echo "$WMII_NORMCOLORS" "$tag"
	fi | wmiir create "/lbar/$tag"
done

wi_eventloop

