#!/bin/sh
# ~/.xsession | ~/.xinitrc
# M. reDD MreDD (at) 0tue0.com
# http://m-redd.com
#
###############################

# Aliases #
x='xinit'

# Font #
xset +fp ${HOME}/.fonts

# Misc #
if [ -f $HOME/.Xmodmap ]; then
    /usr/bin/xmodmap $HOME/.Xmodmap
fi

[ -f /etc/X11/Xmodmap ] && xmodmap /etc/X11/Xmodmap

# Run Apps #
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
xset m 4 1 &
xcompmgr &
xbindkeys &
sabnzbd &
xscreensaver -no-splash &
synergyc belial &
# synergys &
numlockx &
# noip2 -c ~/.noip2.rc &
# xmodmap ~/.Xmodmap &
# multi-dropboxes &
# belial-mredd-sshfs mount &
# pkill -9 g15macro ; g15macro &
# devmon 2>&1 > ~/tmp/devmon.log &
# X setup #
setterm -blank 0 -powersave off -powerdown 0
xset +fp /usr/share/fonts/local &
xset fp rehash &
xset s off
xrdb -merge ~/.Xresources
# Window Manager #
# wistrut $(wmiir read /tag/sel/index | awk '/panel:stalonetray:panel/{print $2}') &
# until wmii; do 
#     true 
# done
until exec ck-launch-session wmii; do 
     true
done#!/bin/sh
# ~/.xsession | ~/.xinitrc
# M. reDD MreDD (at) 0tue0.com
# http://m-redd.com
#
###############################

# Aliases #
x='xinit'

# Font #
xset +fp ${HOME}/.fonts

# Misc #
if [ -f $HOME/.Xmodmap ]; then
    /usr/bin/xmodmap $HOME/.Xmodmap
fi

[ -f /etc/X11/Xmodmap ] && xmodmap /etc/X11/Xmodmap

# Run Apps #
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
xset m 4 1 &
xcompmgr &
xbindkeys &
sabnzbd &
xscreensaver -no-splash &
synergyc belial &
# synergys &
numlockx &
# noip2 -c ~/.noip2.rc &
# xmodmap ~/.Xmodmap &
# multi-dropboxes &
# belial-mredd-sshfs mount &
# pkill -9 g15macro ; g15macro &
# devmon 2>&1 > ~/tmp/devmon.log &
# X setup #
setterm -blank 0 -powersave off -powerdown 0
xset +fp /usr/share/fonts/local &
xset fp rehash &
xset s off
xrdb -merge ~/.Xresources
# Window Manager #
# wistrut $(wmiir read /tag/sel/index | awk '/panel:stalonetray:panel/{print $2}') &
# Normal Start #
# until wmii; do 
#     true 
# done
# Network Manager Start #
until exec ck-launch-session wmii; do 
     true
done
