#!/usr/bin/env bash
# . ~/.bash_stuff/alias_files/misc

# Fortune-mod - Quotes Tools
alias tbbtf-modmaker="sh $HOME/scripts/quote-tools/tbbt.f-mod-maker.sh"
# Various Fun Test
#############
alias bz2="sh $HOME/scripts/bz2.sh"
alias figlet="figlet -d $HOME/.figfonts/ "
alias forcowsay="${R}fortune | ${B}cowsay"
#alias quadconky="sh $HOME/scripts/quad_conky.sh"
#alias rightconky="sh $HOME/scripts/right-conky.sh"
#alias leftconky="sh $HOME/scripts/left-conky.sh"
#alias conky-1="sh $HOME/scripts/conky-scripts/conky-new.sh"
#alias nzbgrab="hellanzb.py enqueuenewzbin "
