#!/usr/bin/env bash
#----------------------------------------------
# file:     ~/.bash_stuff/aliases/android
# author:   Mike Redd - http://m-redd.com/
# vim:fenc=utf-8:nu:ai:si:et:ts=4:sw=4:ft=sh:
#----------------------------------------------

# android
alias android-sdk-update="/opt/android-sdk/tools/android update sdk --no-ui"
#alias android-buildenv="source ~/android/.prep_files/env.sh"
alias screenbuild="screen -c ~/android/.screenrc"

# build scripts
alias buildraum="sh ~/android/scripts/build/build_raum.sh"
alias buildaokpjb="sh ~/android/scripts/build/build_rom-aokp_jb.sh"
alias buildparadigm="sh ~/android/scripts/build/build_rom-bamf_paradigm.sh"

# make commands
alias maketoronlog="make -j12 otapackage 2>&1 | tee toro-build.log"
alias makeraumtnlog="make -j12 otapackage 2>&1 | tee raum-toro-build.log"
alias makeraumgnlog="make -j12 otapackage 2>&1 | tee raum-grouper-build.log"

# tcp/ip
alias modtcp="sudo sysctl -w net.ipv4.tcp_window_scaling=0"

# repo commands
alias reposj1="repo sync -j1"
alias reposfj1="repo sync -f -j1"

alias fetchlmanifest="curl -L -o .repo/local_manifest.xml -O -L https://raw.github.com/pax10/local_manifest/rb/local_manifest.xml"

alias pyfix="source ~/android/.prep_files/android_prep"

# vim: set filetype=bash:
